import java.io.File;
import java.io.IOException;
import java.util.HashSet;

public final class ECommerceApp {

    private Database database;
    private HashSet<String> usernameList;
    //private Cart cart;

    public ECommerceApp() {

        database = new Database();
        usernameList = new HashSet<>();

        database = database.update();
        usernameList = IO.updateUsernameList();


        createDirectories();
        boolean flag = true;

        while (flag) {

            //cart = new Cart(database);

            IO.println("1. Admin login.");
            IO.println("2. Customer login.");
            IO.println("3. Exit the program.");

            int choice = 0;
            try {
                choice = IO.nextInt();
            } catch (Exception e) {
                IO.println("Invalid input! Canceling the operation.");
                continue;
            }

            User user;

            switch (choice) {

                case 1:

                    user = new Administrator(database);
                    user.runSession();
                    break;

                case 2:

                    //TODO add customer login here

                    //user = new Customer(new Cart(database), );
                    user = login();
                    user.runSession();
                    break;

                case 3:
                    IO.println("Revenue generated by Amacon: " + database.getRevenue());
                    IO.println("Exiting the program...");
                    try {
                        database.serialize();
                    } catch (IOException e) {
                        IO.println("Cannot save database to disk.");
                    }
                    try {
                        IO.serializeUsernameList(usernameList);
                    } catch (IOException e) {
                        IO.println("Cannot save usernames to disk.");
                    }
                    flag = false;
                    break;

                default:
                    IO.println("Invalid input. Try again.");
            }
        }
    }

    private final void createDirectories() {

        String[] dirList = {"data/customer/", "data/database"};

        for (String dirName : dirList) {
            File f = new File(dirName);

            if (!f.exists()) {
                f.mkdirs();
            }
        }
    }

    private Customer login() {

        IO.println("Enter username");
        String username = IO.next();

        if (usernameList.contains(username)) {
            Customer customer = null;
            try {
                customer = Customer.deserialize(username);
            } catch (IOException e) {
                IO.println("Cannot retrieve customer: " + username);
            } catch (ClassNotFoundException e) {
                IO.println("Cannot retrieve customer: " + username);
            }
            IO.println("Dear " + username + ", Welcome back!");
            customer.c.setDatabase(database);
            customer.c.setC(customer);

            IO.println("Do you want to continue with your previous cart?\n1. Yes\n2. No");
            int choice=IO.nextInt();

            switch (choice){

                case 1:
                    break;
                case 2:
                    customer.c.reset();
                    break;
            }

            return customer;
        } else {

            usernameList.add(username);
            Customer customer = new Customer(new Cart(database), username);
            IO.println("Dear " + username + ", Welcome to Amacon.com!");
            IO.println("You have been successfully registered!");
            return customer;
        }
        //return null;
    }
}
